# Tensor
- 우리는 numpy라는 라이브러리를 사용해 array(모든 차원)라는 형태로 다룬다

In [3]:
import numpy as np

## 0차원
- scalar

In [4]:
# 숫자 데이터를 array화
arr = np.array(17)
arr

array(17)

In [5]:
type(17), type(arr)

(int, numpy.ndarray)

In [6]:
# 차원이 없다
arr.shape

()

In [7]:
arr.ndim

0

## 1차원
- 대괄호로 차원을 추가할 수 있다

In [8]:
arr = np.array([17,6])
arr

array([17,  6])

In [9]:
arr.shape

(2,)

In [10]:
arr.ndim

1

In [11]:
# shape에 있는 숫자 자체가 차원이 아니라 숫자의 개수가 차원!
# 즉 1차원에 3개의 값이 들어갔다는 의미
_arr = np.array([1, 2, 3])
print(_arr)
print(_arr.shape)
print(_arr.ndim)

[1 2 3]
(3,)
1


## 2차원
- 1차원처럼 같은 방법으로 차원 추가

In [12]:
arr = np.array([[1, 2, 3]])
arr, arr.shape, arr.ndim

(array([[1, 2, 3]]), (1, 3), 2)

In [13]:
arr = np.array([[1, 2, 3], [1, 2, 3]])
arr, arr.shape, arr.ndim

(array([[1, 2, 3],
        [1, 2, 3]]),
 (2, 3),
 2)

In [ ]:
# 대괄호의 개수로 차원이 정해짐
arr = np.array([[17]])
print(arr.shape)
print(arr.ndim)

## 다차원
- Enter로 보기 편하게 쓸 수 있다

In [ ]:
arr=np.array([[[[1,2,3],[1,2,3],[1,2,3]],
               [[1,2,3],[1,2,3],[1,2,3]]],
              [[[1,2,3],[1,2,3],[1,2,3]],
               [[1,2,3],[1,2,3],[1,2,3]]]])

print(arr)
print(arr.shape) 
print(arr.ndim)

In [ ]:
arr=np.array([[[1],[2],[3]],[[1],[2],[3]],[[1],[2],[3]]])
print(arr)
print(arr.shape) 
print(arr.ndim)

In [15]:
# 차원을 확인하는 다른 방법
arr = np.array([[1, 2, 3], [1, 2, 3]])
arr.ndim, len(arr.shape)

(2, 2)

cf) 대괄호 개수로 보면 편하긴 하지만 모든 값들이 담긴 수가 같아야 한다

In [14]:
arr=np.array([[[1],[2,3],[3,4,5]],[[1],[2],[3]]])
print(arr)
print(arr.shape) 
print(arr.ndim)

[[list([1]) list([2, 3]) list([3, 4, 5])]
 [list([1]) list([2]) list([3])]]
(2, 3)
2


<ipython-input-14-dfbe42ff14b6>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr=np.array([[[1],[2,3],[3,4,5]],[[1],[2],[3]]])


## size

In [ ]:
arr = np.array([[1, 2, 3], [1, 2, 3]])
arr.size # 2 X 3 = 6
# arr.shape

# data type
- 똑같이 생긴 array도 data type이 다르면 다른 array
- Gray Scale의 Image인 경우 OpenCV에서 np.uint8

In [16]:
arr = np.array([[1, 2, 3], [1, 2, 3]]) 
arr1 = np.array([[1., 2, 3], [1, 2, 3]])
arr.dtype, arr1.dtype

(dtype('int32'), dtype('float64'))

- 형변환

In [17]:
arr1.astype('float32')

array([[1., 2., 3.],
       [1., 2., 3.]], dtype=float32)

In [27]:
arr1.astype('int8')

array([[1, 2, 3],
       [1, 2, 3]], dtype=int8)

In [29]:
arr2 = arr1.astype(np.uint8)

In [30]:
arr2

array([[1, 2, 3],
       [1, 2, 3]], dtype=uint8)

- array 자체를 형변환 할때는 앞에 array이름을 다시 넣어줘야 한다

In [22]:
arr1.dtype

dtype('float64')

In [23]:
arr1 = arr1.astype(np.uint8)
arr1

array([[1, 2, 3],
       [1, 2, 3]], dtype=uint8)

- 처음 array를 만들 때 dtype을 선언할 수 있다

In [24]:
arr1 = np.array([[1, 2, 3], [1, 2, 3]], dtype=np.uint8)
arr1.dtype

dtype('uint8')

# Reshape

In [31]:
arr = np.array([[1, 2, 3], [1, 2, 3]])
arr.shape

(2, 3)

In [32]:
# size는 같아야 한다
arr = arr.reshape([1, 6])
arr

array([[1, 2, 3, 1, 2, 3]])

In [33]:
arr = np.array([[1, 2, 3], [1, 2, 3]])
arr = arr.reshape([6])
arr

array([1, 2, 3, 1, 2, 3])

In [34]:
# -1: 남는 숫자
arr = np.array([[1, 2, 3], [1, 2, 3]])
arr = arr.reshape(-1)
print(arr)
print(arr.shape)

[1 2 3 1 2 3]
(6,)


In [35]:
arr = np.array([[1, 2, 3], [1, 2, 3]])

arr = arr.reshape(-1, 3)
print(arr, arr.shape)

arr = arr.reshape(2, -1)
print(arr, arr.shape)

[[1 2 3]
 [1 2 3]] (2, 3)
[[1 2 3]
 [1 2 3]] (2, 3)


In [36]:
arr = np.random.randn(8, 8) # 표준정규분포로부터 샘플링
arr.shape

(8, 8)

In [37]:
arr = arr.reshape([32, 2])
print(arr.shape)
print(arr)

(32, 2)
[[-1.31046958 -0.93253738]
 [-2.13819828  1.79162807]
 [-0.16228284 -1.70694717]
 [-0.23222206 -0.73382067]
 [-1.07183769 -0.83064369]
 [-0.7473042  -0.2965974 ]
 [ 0.65594838  0.17794284]
 [-0.1542058  -0.05729906]
 [-0.33206404 -1.02355202]
 [ 0.60192929  0.07359752]
 [-1.00384314  1.34217908]
 [ 0.69170877 -0.67502613]
 [-1.37150749 -0.02806462]
 [ 0.91914374 -1.71732504]
 [ 0.01925313 -0.95089916]
 [ 1.39302547 -1.06284878]
 [ 0.19263793  0.9511688 ]
 [-1.35258785  0.04488959]
 [ 0.47808845 -0.35219241]
 [ 0.65993249 -0.25650158]
 [-1.49616979 -0.88013121]
 [ 0.20966962 -0.47516489]
 [ 0.30906106  0.38845719]
 [-1.6757788   1.33412496]
 [-2.18297148  0.05834462]
 [ 0.76907619  1.91390185]
 [ 0.05506726  2.03486045]
 [-0.37140426  0.5972738 ]
 [-0.05129632 -0.81239152]
 [-1.04038791  1.54781763]
 [-1.55012918 -0.24270387]
 [ 0.45244546  0.51919239]]


In [38]:
# 차원을 늘릴 수 있다
arr = arr.reshape([-1, 2, 1])
print(arr.shape)

arr = arr.reshape(-1, 2, 1)
print(arr.shape)

arr = arr.reshape(-1, 1, 4, 1, 2, 1, 1)
print(arr.shape)
arr

(32, 2, 1)
(32, 2, 1)
(8, 1, 4, 1, 2, 1, 1)


array([[[[[[[-1.31046958]],

           [[-0.93253738]]]],



         [[[[-2.13819828]],

           [[ 1.79162807]]]],



         [[[[-0.16228284]],

           [[-1.70694717]]]],



         [[[[-0.23222206]],

           [[-0.73382067]]]]]],





       [[[[[[-1.07183769]],

           [[-0.83064369]]]],



         [[[[-0.7473042 ]],

           [[-0.2965974 ]]]],



         [[[[ 0.65594838]],

           [[ 0.17794284]]]],



         [[[[-0.1542058 ]],

           [[-0.05729906]]]]]],





       [[[[[[-0.33206404]],

           [[-1.02355202]]]],



         [[[[ 0.60192929]],

           [[ 0.07359752]]]],



         [[[[-1.00384314]],

           [[ 1.34217908]]]],



         [[[[ 0.69170877]],

           [[-0.67502613]]]]]],





       [[[[[[-1.37150749]],

           [[-0.02806462]]]],



         [[[[ 0.91914374]],

           [[-1.71732504]]]],



         [[[[ 0.01925313]],

           [[-0.95089916]]]],



         [[[[ 1.39302547]],

           [[-1.06284878]]]]]

## 1차원으로 펼쳐주기
- arr.ravel()

In [40]:
arr = arr.ravel()
arr.shape

(64,)

In [41]:
arr.ndim 

1

In [42]:
arr == arr.reshape(-1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

# 차원을 늘리기
- np.expand_dims()

In [43]:
arr.shape

(64,)

In [44]:
arr = np.expand_dims(arr, 0) # 앞에다가 한 차원을 추가
print(arr.shape)

(1, 64)


In [45]:
arr = arr.ravel()
arr = np.expand_dims(arr, -1) # 뒤에다가 한 차원을 추가
print(arr.shape)

(64, 1)


In [46]:
arr = arr.ravel()
arr = np.expand_dims(np.expand_dims(arr,-1), 0)
arr.shape

(1, 64, 1)

# array 생성하기

In [47]:
zeros = np.zeros([3, 3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
zeros = np.zeros(1)
print(zeros)
print(zeros.ndim)

zeros = np.zeros([1])
print(zeros)
print(zeros.ndim)

[0.]
1
[0.]
1


In [49]:
ones = np.ones([10, 5])
print(ones)
print(ones.ndim)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
2


In [50]:
ones * 127

array([[127., 127., 127., 127., 127.],
       [127., 127., 127., 127., 127.],
       [127., 127., 127., 127., 127.],
       [127., 127., 127., 127., 127.],
       [127., 127., 127., 127., 127.],
       [127., 127., 127., 127., 127.],
       [127., 127., 127., 127., 127.],
       [127., 127., 127., 127., 127.],
       [127., 127., 127., 127., 127.],
       [127., 127., 127., 127., 127.]])

In [52]:
arr = np.arange(5)
print(arr)

arr = np.arange(10, 18)
print(arr)

arr = np.arange(10, 20, 2)
print(arr)

[0 1 2 3 4]
[10 11 12 13 14 15 16 17]
[10 12 14 16 18]


In [53]:
# arange는 무조건 1차원으로 만들어줌
arr = np.arange(36).reshape(3, 12)
print(arr, arr.shape)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31 32 33 34 35]] (3, 12)


# Indexing & Slicing

In [55]:
# list
nums = [1, 2, 3, 4, 5]
print(nums[2], nums[1:])
nums = [1, 2, 3, 4, [1, 2, 3]]
print(nums[4])
print(nums[4][1])

3 [2, 3, 4, 5]
[1, 2, 3]
2


In [56]:
# array
print(arr)
print(arr[2])
print(arr[2][5])
print(arr[2][-1])
print(arr[2, -1])
print(arr[1:])
print(arr[1:, 5:])

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31 32 33 34 35]]
[24 25 26 27 28 29 30 31 32 33 34 35]
29
35
35
[[12 13 14 15 16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31 32 33 34 35]]
[[17 18 19 20 21 22 23]
 [29 30 31 32 33 34 35]]


## Boolean Indexing

In [ ]:
data = np.random.randn(3, 5)
data

In [ ]:
# array의 data마다 boolean을 반환
data <= 0

In [ ]:
print(data[data<=0])
data[data<=0] = 1
data

# Broadcast
- 연산하려는 서로 다른 두 개의 행렬의 shape가 같지 않지만 한쪽의 차원이라도 같거나 값의 개수가 한 개일때 이를 여러 복사를 하여 연산을 함

In [ ]:
arr = np.arange(9).reshape(3, 3)
arr

In [ ]:
arr + 3

In [ ]:
arr * 3

In [ ]:
arr + np.array([1, 1, 2])

# Math Function

In [ ]:
arr + arr

In [ ]:
np.add(arr, 2)

In [ ]:
np.multiply(arr, 5)

In [ ]:
arr = np.random.randint(7, size=27).reshape(3, 3, 3) # 0~6까지 랜덤한 정수 샘플링
arr_2 = np.random.randint(3, size=9).reshape(3, 3)
print(arr, '\n','\n',  arr.shape, '\n', '\n', arr_2, '\n', '\n', arr_2.shape)

In [ ]:
arr + arr_2

In [ ]:
np.sum(arr)

In [ ]:
np.sum(arr+arr_2)

In [ ]:
np.max(arr)

In [ ]:
np.max(arr+arr_2)

In [ ]:
np.min(arr+arr_2)

## axis

In [ ]:
print(arr+arr_2, '\n')
print((arr+arr_2).shape, '\n')
# 바깥에서부터 구분하는 차원을 없애고 각각 거기에 대해서 비교
print(np.max(arr+arr_2, axis=0))
print(np.max(arr+arr_2, axis=1))
print(np.max(arr+arr_2, axis=2))
print(np.max(arr+arr_2, axis=-1))

In [ ]:
# 기준 차원 빼고 나머지 좌표가 같은 것끼리 더한다고 생각해도 됨
# (결과의 shape도 그 axis만큼 줄어듬)
print(arr+arr_2, '\n')
print(np.sum(arr+arr_2, axis=0))
print(np.sum(arr+arr_2, axis=1))
print(np.sum(arr+arr_2, axis=2))

In [ ]:
arr = np.arange(4*2*4).reshape([4, 2, 4])
print(arr)
print(arr.sum(axis=0))
print(arr.sum(axis=0).shape)
print(arr.sum(axis=1))
print(arr.sum(axis=1).shape)
print(arr.sum(axis=-1))
print(arr.sum(axis=-1).shape)

In [ ]:
np.mean(arr)

In [ ]:
arr = np.array([1, 6, 7, 15, 2, -9])
np.argmax(arr)

In [ ]:
np.argmin(arr)

In [ ]:
arr = np.array([[[15, 5, 9], [2, 7, 6]],
                [[5, 9, 10], [1, 98, 2]]])
print(arr.shape)
print(arr.argmax(axis=0))
print(arr.argmax(axis=1))
print(arr.argmax(axis=-1))

# unique

In [ ]:
arr = np.array([3, 5, 6, 6, 1, 2, 3, 4, 5, 6, 8, 8, 10, 11, 2])
np.unique(arr)