In [1]:
import numpy as np

# scalar
arr=np.array(17)
arr

array(17)

In [3]:
type(17), type(arr)

(int, numpy.ndarray)

In [4]:
arr.shape

()

In [7]:
arr.ndim

0

In [9]:
# 1차원 Vector
arr=np.array([1,2])
arr

array([1, 2])

In [13]:
arr.shape

(2,)

In [14]:
arr.ndim

1

In [15]:
arr3=np.array([1,2,3])

In [16]:
arr3.shape

(3,)

In [17]:
# 2차원 Matrix
arr=np.array([[1,2,3], [2,3,4]])
arr

array([[1, 2, 3],
       [2, 3, 4]])

In [18]:
arr.shape # Matrix 의 (행개수, 열 개수)를 반환

(2, 3)

In [19]:
arr.ndim

2

In [22]:
# 다차원 Tensor
arr=np.array([[[1,2,3],[1,2,3]],[[2,3,4],[4,5,6]]])
# 맨 앞에 대괄호 개수가 차원과 같다. 이 경우는 3차원
arr.shape
# 제일 바깥괄호 부터 안으로 들어감

(2, 2, 3)

In [23]:
arr.ndim

3

In [25]:
len(arr.shape) # shape 의 요소 개수와 차원은 같다.

3

In [26]:
# size
arr.size # 2 X 2 X 3 = 12

12

In [28]:
# data type => .dtype
arr = np.array([[1, 2, 3], [1, 2, 3]]) 
arr1 = np.array([[1., 2, 3], [1, 2, 3]])
arr.dtype, arr1.dtype

(dtype('int32'), dtype('float64'))

In [38]:
# 형변환
arr1.astype('float32')

array([[1., 2., 3.],
       [1., 2., 3.]], dtype=float32)

In [43]:
arr1.astype('int8')

array([[1, 2, 3],
       [1, 2, 3]], dtype=int8)

In [44]:
arr2 = arr1.astype(np.uint8)

In [45]:
arr2

array([[1, 2, 3],
       [1, 2, 3]], dtype=uint8)

In [48]:
arr1.dtype 
# 이 셀의 실행결과를 보면 arr1은 
# 선언을 해주지 않는한 변하지 않았음을 알 수 있다. 

dtype('uint8')

In [49]:
arr1=arr1.astype(np.uint8)
arr1

array([[1, 2, 3],
       [1, 2, 3]], dtype=uint8)

In [52]:
arr1=np.array([[1,2,3],[1,2,3]], dtype=np.uint8)
arr1.dtype

dtype('uint8')

In [53]:
# Reshape

arr1=np.array([[1,2,3],[1,2,3]])
arr.shape

(2, 3)

In [56]:
arr_re=arr.reshape(3,-1)
arr_re

array([[1, 2],
       [3, 1],
       [2, 3]])

In [58]:
# arnage
a= [1,2,3,4,5]
b= np.arange(5)
c= np.arange(1,10,1) # 10 (마지막 숫자)은 포함을 안함

print(a,b,c)

[1, 2, 3, 4, 5] [0 1 2 3 4] [1 2 3 4 5 6 7 8 9]


In [62]:
A=np.arange(9)+1
A=A.reshape(3,3)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
B=A[1:,1:]
B

array([[5, 6],
       [8, 9]])